on:
  push:
    branches:
      - stable
      - dev
  pull_request:
    branches:
      - stable
      - dev

name: Tests

jobs:
  misc_tests:
    name: Misc tests
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        tox_env:
          - lint
          - format
          - security
    runs-on: ubuntu-latest

  unit_test:
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: krb5-devel openldap-devel
    strategy:
      matrix:
        tox_env:
          - py38-unittest
          - py39-unittest
          - py310-unittest
          - py311-unittest
    runs-on: ubuntu-latest
